---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.project_name }}
  annotations:
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: service
  owner: user:guest
  lifecycle: production
