---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.project_name }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: production
  providesApis:
  - ${{ values.project_name }}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.project_name }}-api
  description: The ${{ values.project_name }} REST API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $openapi: https://github.com/BlakeHolifield/consoledot-go-starter-app/blob/master/docs/swagger.yaml
