apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: consoledot-starter-app-env
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdEnvironment
  metadata:
    name: env-starter-app
    namespace: ${NAMESPACE}
  spec:
    providers:
      db:
        mode: local
      deployment:
        omitPullPolicy: true
      web:
        images: {}
        ingressClass: openshift-default
        mode: local
        port: 8000
        privatePort: 10000
        tls: {}
      inMemoryDb:
        mode: none
      kafka:
        mode: none
      logging:
        mode: none
      objectStore:
        mode: none
    resourceDefaults:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 30m
        memory: 128Mi
    targetNamespace: ${NAMESPACE}
parameters:
- description: Namespace to deploy into
  name: NAMESPACE
  value: ${NAMESPACE}