---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${{ values.project_name }}
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ${CLOWDAPP_NAME}
    namespace: ${NAMESPACE}
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: ${{ values.project_name }}-api-server
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          httpGet:
            path: /livez
            port: 8000
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
      webServices:
        public:
          enabled: true
          apiPath: ${{ values.project_name }}-api
          whitelistPaths:
          - /livez
          - /readyz
          - /api/${{ values.project_name }}/*
    database:
      name: ${DB_NAME}
      version: 12
parameters:
- description: Name of the ClowdApp
  name: CLOWDAPP_NAME
  value: ${{ values.project_name }}
- description: ClowdEnvironment name
  name: ENV_NAME
  value: stage
- description: Database Name
  name: DB_NAME
  value: ${{ values.project_name }}-db
- description: Namespace to deploy into
  name: NAMESPACE
  value: ${NAMESPACE}
- description: App Image
  name: IMAGE
  value: ${IMAGE}
- description: Image Tag
  name: IMAGE_TAG
  value: ${IMAGE_TAG}
