basePath: /api/starter-app-api/v1
info:
  contact:
    email: addrew@redhat.com
    name: Adam Drew
  description: This is a sample API for the ConsoleDot Go Starter App.
  title: ConsoleDot Go Starter App API
  version: "1.0"
paths:
  /api/starter-app-api/v1/db-info:
    get:
      description: Query the API to get some database informaiton
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get database info
      tags:
      - api
  /api/starter-app-api/v1/hello:
    get:
      description: Recieve a greeting from the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Recieve a greeting
      tags:
      - api
  /healthz:
    get:
      description: Determines if application is still alive
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Determines if application is still alive
      tags:
      - probes
  /readyz:
    get:
      description: Determines readiness of the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Determines readiness of the application
      tags:
      - probes
swagger: "2.0"
